// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Useful.Tests.Security.Cryptography
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("MonoAlphabeticSpecFlow")]
    public partial class MonoAlphabeticSpecFlowFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "MonoAlphabeticSpecFlow.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "MonoAlphabeticSpecFlow", "In order to use the Monoalphabetic Substitution cipher\r\nAs a cryptographer\r\nI wan" +
                    "t to test encryption and decryption", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Test the Monoalphabetic Substitution cipher")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void TestTheMonoalphabeticSubstitutionCipher()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Test the Monoalphabetic Substitution cipher", new string[] {
                        "mytag"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "TransformMode",
                        "Key",
                        "IV",
                        "Plaintext",
                        "Ciphertext",
                        "NewIV",
                        "Notes"});
            table1.AddRow(new string[] {
                        "Encrypt",
                        "ABC|AB|True",
                        "",
                        "ABC",
                        "BAC",
                        "",
                        "Basic Symmetric Encryption"});
            table1.AddRow(new string[] {
                        "Encrypt",
                        "ABCD|AB CD|True",
                        "",
                        "ABCD",
                        "BADC",
                        "",
                        "Multiple Substitution pairs"});
            table1.AddRow(new string[] {
                        "Encrypt",
                        "ABC|AB BC CA|False",
                        "",
                        "ABC",
                        "BCA",
                        "",
                        "Basic Asymmetric Encryption"});
            table1.AddRow(new string[] {
                        "Encrypt",
                        "ABC||True",
                        "",
                        "ABC",
                        "ABC",
                        "",
                        "No Substitutions"});
            table1.AddRow(new string[] {
                        "Encrypt",
                        "ABCD||True",
                        "",
                        "ABÅCD",
                        "ABÅCD",
                        "",
                        "Disallowed chars"});
            table1.AddRow(new string[] {
                        "Decrypt",
                        "ABCD|AB CD|True",
                        "",
                        "ABCD",
                        "BADC",
                        "",
                        "Basic Symmetric Decryption"});
            table1.AddRow(new string[] {
                        "Decrypt",
                        "ABC|AB BC CA|False",
                        "",
                        "ABC",
                        "BCA",
                        "",
                        "Basic Asymmetric Decryption"});
            table1.AddRow(new string[] {
                        "Encrypt",
                        "ABCD|AB CD|True",
                        "",
                        "AB CD",
                        "BA DC",
                        "",
                        "Whitespace"});
            table1.AddRow(new string[] {
                        "Encrypt",
                        "ABCDEFGHIJKLMNOPQRSTUVWXYZ|AB CD EF GH|True",
                        "",
                        "HeLlOwOrLd",
                        "GeLlOwOrLd",
                        "",
                        "Mixed case"});
            table1.AddRow(new string[] {
                        "Decrypt",
                        "ABCDEFGHIJKLMNOPQRSTUVWXYZ|AB CD EF GH|True",
                        "",
                        "HeLlOwOrLd",
                        "GeLlOwOrLd",
                        "",
                        "Mixed case"});
#line 8
 testRunner.Given("I am testing Monoalphabetic:", ((string)(null)), table1, "Given ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
